# This file describes which services are required by this application
# in order for the smoke tests on the TEST environment and end to end tests
# on the STAGE environment to pass

# lowercase name of the environment
test:
  # list of required services
  services:
    # type and name of the service
    - type: rabbitmq
      name: rabbitmq-github-analytics
    - type: mysql
      name: mysql-github-analytics
    - type: eureka
      name: eureka-github-analytics
      coordinates: scpipelines/github-eureka:latest
    - type: stubrunner
      name: stubrunner-github-analytics
      coordinates: scpipelines/github-analytics-stub-runner-boot-classpath-stubs:latest
      useClasspath: true
stage:
  services:
    - type: rabbitmq
      name: github-rabbitmq
    - type: mysql
      name: mysql-github
    - type: eureka
      name: github-eureka
      coordinates: scpipelines/github-eureka:latest
